### ISSUE TITLE
Extracting the difference in time between messages sent and receveived

### ISSUE THREAD

**Issue by durnezj** [openskynetwork/dump1090-hptoa#5]
Hello,

After I read your paper on this subject, i want to use this to make a localisation solution myself. Therefore I need to be able to get the time difference between sending the message from the aircraft and receiving it, as accurate as possible. Is there any way to do this in the software or can you point me to the code where this can be calculated.

It would help me a great deal, it's part of my thesis!

Thanks in advance.

**Comment by fabioricciato** [comment]
Hi

it's not possible to measure the departure (transmission) time of the
message, but only the arrival (reception) time. However, this is enough to
localise the aircraft if the same message is received by multiple
receivers. There are several publications on this topic, one of them could
be this one
https://telematics.poliba.it/publications/2018/RicciatoTMC2018.pdf
but there are many others that address specifically aircraft localization.

good luck with your thesis
fabio

**Comment by durnezj** [comment]
Thanks for you reply, it will help a lot. :)
